structure I = IntFromTo(FixedInt)
structure T = TestFromToString(open I val name="FixedInt")
structure I = IntFromTo(Int)
structure T = TestFromToString(open I val name="Int")
structure I = IntFromTo(Int10)
structure T = TestFromToString(open I val name="Int10")
structure I = IntFromTo(Int11)
structure T = TestFromToString(open I val name="Int11")
structure I = IntFromTo(Int12)
structure T = TestFromToString(open I val name="Int12")
structure I = IntFromTo(Int13)
structure T = TestFromToString(open I val name="Int13")
structure I = IntFromTo(Int14)
structure T = TestFromToString(open I val name="Int14")
structure I = IntFromTo(Int15)
structure T = TestFromToString(open I val name="Int15")
structure I = IntFromTo(Int16)
structure T = TestFromToString(open I val name="Int16")
structure I = IntFromTo(Int17)
structure T = TestFromToString(open I val name="Int17")
structure I = IntFromTo(Int18)
structure T = TestFromToString(open I val name="Int18")
structure I = IntFromTo(Int19)
structure T = TestFromToString(open I val name="Int19")
structure I = IntFromTo(Int20)
structure T = TestFromToString(open I val name="Int20")
structure I = IntFromTo(Int21)
structure T = TestFromToString(open I val name="Int21")
structure I = IntFromTo(Int22)
structure T = TestFromToString(open I val name="Int22")
structure I = IntFromTo(Int23)
structure T = TestFromToString(open I val name="Int23")
structure I = IntFromTo(Int24)
structure T = TestFromToString(open I val name="Int24")
structure I = IntFromTo(Int25)
structure T = TestFromToString(open I val name="Int25")
structure I = IntFromTo(Int26)
structure T = TestFromToString(open I val name="Int26")
structure I = IntFromTo(Int27)
structure T = TestFromToString(open I val name="Int27")
structure I = IntFromTo(Int28)
structure T = TestFromToString(open I val name="Int28")
structure I = IntFromTo(Int29)
structure T = TestFromToString(open I val name="Int29")
structure I = IntFromTo(Int30)
structure T = TestFromToString(open I val name="Int30")
structure I = IntFromTo(Int31)
structure T = TestFromToString(open I val name="Int31")
structure I = IntFromTo(Int32)
structure T = TestFromToString(open I val name="Int32")
structure I = IntFromTo(Int4)
structure T = TestFromToString(open I val name="Int4")
structure I = IntFromTo(Int5)
structure T = TestFromToString(open I val name="Int5")
structure I = IntFromTo(Int6)
structure T = TestFromToString(open I val name="Int6")
structure I = IntFromTo(Int64)
structure T = TestFromToString(open I val name="Int64")
structure I = IntFromTo(Int7)
structure T = TestFromToString(open I val name="Int7")
structure I = IntFromTo(Int8)
structure T = TestFromToString(open I val name="Int8")
structure I = IntFromTo(Int9)
structure T = TestFromToString(open I val name="Int9")
structure I = IntFromTo(IntInf)
structure T = TestFromToString(open I val name="IntInf")
structure I = IntFromTo(LargeInt)
structure T = TestFromToString(open I val name="LargeInt")
